[[redirects]]
  from = "https://www.datacost.co.za/*"
  to = "https://datacost.co.za/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.datacost.co.za/*"
  to = "https://datacost.co.za/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://datacost.co.za/*"
  to = "https://datacost.co.za/:splat"
  status = 301
  force = true
