import { Bundle, NetworkStats, NetworkMetadata, NetworkName } from './types';

const PRICE_REVIEW_DATE = '2026-08-01';

const SOURCES = {
  mtnInternetBundles: {
    sourceUrl: 'https://www.mtn.co.za/home/terms-and-conditions/content/mtn-internet-bundles',
    sourceLabel: 'MTN Internet Bundles terms'
  },
  mtnWhatsappBundles: {
    sourceUrl: 'https://onlinecms.mtn.co.za/sites/default/files/whatsapp-bundles.pdf',
    sourceLabel: 'MTN WhatsApp Bundles terms'
  },
  mtnNightExpress: {
    sourceUrl: 'https://www.mtn.co.za/home/terms-and-conditions/content/mtn-night-express-data-bundles',
    sourceLabel: 'MTN Night Express terms'
  },
  vodacomOpenMarketBundles: {
    sourceUrl: 'https://www.vodacom.co.za/vodacom/shopping/plans/open-market-bundle-price-changes',
    sourceLabel: 'Vodacom open-market bundle price changes'
  },
  vodacomPrepaidLte: {
    sourceUrl: 'https://www.vodacom.co.za/vodacom/shopping/plans/prepaid-plans',
    sourceLabel: 'Vodacom prepaid LTE data page'
  },
  vodacomPrepaidData: {
    sourceUrl: 'https://www.vodacom.co.za/vodacom/shopping/data/prepaid-data',
    sourceLabel: 'Vodacom prepaid data page'
  },
  telkomTimeBasedBundles: {
    sourceUrl: 'https://www.telkom.co.za/prepaid-services/time-based-bundle',
    sourceLabel: 'Telkom time-based bundles'
  },
  telkomWhatsappBundles: {
    sourceUrl: 'https://www.telkom.co.za/prepaid-services/whatsapp-bundle',
    sourceLabel: 'Telkom WhatsApp bundles'
  },
  cellcDataBundles: {
    sourceUrl: 'https://www.cellc.co.za/cellc/get-databundles',
    sourceLabel: 'Cell C data bundle catalogue'
  },
  cellcWhatsappBundles: {
    sourceUrl: 'https://www.cellc.co.za/cellc/jsp/pinless-recharge/rechargeBundle_ajax.jsp?bundleCategory=WhatsApp&bundleType=WhatsApp',
    sourceLabel: 'Cell C WhatsApp bundle catalogue'
  },
  rainHome: {
    sourceUrl: 'https://www.rain.co.za/5Ghomewifi',
    sourceLabel: 'Rain unlimited home 5G page'
  }
} as const;

export const networkMetadata: Record<NetworkName, NetworkMetadata> = {
  Vodacom: {
    name: 'Vodacom',
    color: '#E60000',
    textColor: '#FFFFFF',
    logoLetter: 'V',
    description: 'Vodacom is usually a coverage-first option in many urban and suburban areas.',
    ussdBalance: '*135#',
    externalUrl: 'https://www.vodacom.co.za',
  },
  MTN: {
    name: 'MTN',
    color: '#FFCC00',
    textColor: '#031636',
    logoLetter: 'M',
    description: 'MTN is often a balanced option for users comparing coverage, promotions, and monthly value.',
    ussdBalance: '*136#',
    externalUrl: 'https://www.mtn.co.za',
  },
  Telkom: {
    name: 'Telkom',
    color: '#0066CC',
    textColor: '#FFFFFF',
    logoLetter: 'T',
    description: 'Telkom is often competitive for prepaid users who prioritize lower cost per GB.',
    ussdBalance: '*188#',
    externalUrl: 'https://www.telkom.co.za',
  },
  'Cell C': {
    name: 'Cell C',
    color: '#1a1c1c',
    textColor: '#FFFFFF',
    logoLetter: 'C',
    description: 'Cell C uses a national dual-MOCN model across MTN and Vodacom radio access networks; local experience can vary.',
    ussdBalance: '*101#',
    externalUrl: 'https://www.cellc.co.za',
  },
  Rain: {
    name: 'Rain',
    color: '#FF4400',
    textColor: '#FFFFFF',
    logoLetter: 'R',
    description: 'Rain focuses on online-account-managed unlimited-style data plans in supported coverage areas.',
    ussdBalance: 'N/A (App or web)',
    externalUrl: 'https://www.rain.co.za',
  },
};

export const bundles: Bundle[] = [
  {
    id: 'mtn-monthly-5gb',
    slug: 'mtn-5gb-data-price',
    network: 'MTN',
    name: 'MTN Monthly 5GB Anytime + 5GB Night Express',
    price: 299,
    volume: '5GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '5GB',
    nightData: '5GB',
    costPerGb: 59.8,
    bestFor: 'Monthly users who can use the Night Express allocation',
    watchOut: 'Half of the included data is restricted to Night Express hours',
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'mtn-monthly-1gb',
    slug: 'mtn-1gb-data-price',
    network: 'MTN',
    name: 'MTN Monthly 1GB',
    price: 79,
    volume: '1GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '1GB',
    costPerGb: 79,
    bestFor: 'Entry-level monthly option',
    watchOut: 'Higher cost per GB than larger bundles',
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'mtn-hourly-150mb',
    slug: 'mtn-hourly-150mb-data-price',
    network: 'MTN',
    name: 'MTN Hourly 150MB',
    price: 8,
    volume: '150MB',
    validity: '1 Hour',
    type: 'Hourly',
    anytimeData: '150MB',
    costPerGb: 53.33,
    bestFor: 'Quick short-session usage',
    watchOut: 'Very short validity (1 hour)',
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'mtn-daily-200mb',
    slug: 'mtn-daily-200mb-data-price',
    network: 'MTN',
    name: 'MTN Daily 200MB',
    price: 15,
    volume: '200MB',
    validity: '1 Day',
    type: 'Daily',
    anytimeData: '200MB',
    costPerGb: 75,
    bestFor: 'Light daily usage',
    watchOut: 'Short validity (1 day)',
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'mtn-daily-1-5gb',
    slug: 'mtn-daily-1-5gb-data-price',
    network: 'MTN',
    name: 'MTN Daily 1.5GB',
    price: 33,
    volume: '1.5GB',
    validity: '1 Day',
    type: 'Daily',
    anytimeData: '1.5GB',
    costPerGb: 22,
    bestFor: 'Higher-volume short-term use',
    watchOut: 'Short validity (1 day)',
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'mtn-weekly-500mb',
    slug: 'mtn-weekly-500mb-data-price',
    network: 'MTN',
    name: 'MTN Weekly 500MB',
    price: 50,
    volume: '500MB',
    validity: '7 Days',
    type: 'Weekly',
    anytimeData: '500MB',
    costPerGb: 100,
    bestFor: 'Moderate weekly usage',
    watchOut: 'Higher cost per GB than monthly bundles',
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'mtn-weekly-1-2gb',
    slug: 'mtn-weekly-1-2gb-data-price',
    network: 'MTN',
    name: 'MTN Weekly 1.2GB',
    price: 69,
    volume: '1.2GB',
    validity: '7 Days',
    type: 'Weekly',
    anytimeData: '1.2GB',
    costPerGb: 57.5,
    bestFor: 'Weekly top-up without monthly commitment',
    watchOut: 'Can be expensive if repeated every week',
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'mtn-night-250mb',
    slug: 'mtn-night-250mb-data-price',
    network: 'MTN',
    name: 'MTN Night Express 250MB',
    price: 5,
    volume: '250MB',
    validity: '1 Night',
    type: 'Daily',
    anytimeData: '0MB',
    nightData: '250MB',
    costPerGb: 20,
    bestFor: 'Late-night downloads',
    watchOut: 'Night-only usage window (00:01-04:59)',
    ...SOURCES.mtnNightExpress,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'night_data',
    nightWindow: '00:01-04:59',
  },
  {
    id: 'mtn-whatsapp-weekly-1gb',
    slug: 'mtn-whatsapp-weekly-1gb-data-price',
    network: 'MTN',
    name: 'MTN WhatsApp 1GB Weekly',
    price: 22,
    volume: '1GB',
    validity: '7 Days',
    type: 'Social',
    anytimeData: '1GB (WhatsApp)',
    costPerGb: 22,
    bestFor: 'Chat-first users',
    note: 'App-specific bundle',
    watchOut: 'Social-only access, not full internet',
    ...SOURCES.mtnWhatsappBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'promo_campaign_offer',
  },
  {
    id: 'voda-hourly-50mb',
    slug: 'vodacom-hourly-50mb-data-price',
    network: 'Vodacom',
    name: 'Vodacom Hourly 50MB',
    price: 5,
    volume: '50MB',
    validity: '1 Hour',
    type: 'Hourly',
    anytimeData: '50MB',
    costPerGb: 100,
    bestFor: 'Emergency top-up for quick low-data tasks',
    watchOut: 'Very short validity (1 hour)',
    ...SOURCES.vodacomPrepaidData,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'voda-weekly-750mb',
    slug: 'vodacom-weekly-750mb-data-price',
    network: 'Vodacom',
    name: 'Vodacom Weekly 750MB',
    price: 55,
    volume: '750MB',
    validity: '7 Days',
    type: 'Weekly',
    anytimeData: '750MB',
    costPerGb: 73.33,
    bestFor: 'Moderate users who recharge weekly',
    watchOut: 'Higher cost per GB than larger packs',
    ...SOURCES.vodacomOpenMarketBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'voda-weekly-1-5gb',
    slug: 'vodacom-weekly-1-5gb-data-price',
    network: 'Vodacom',
    name: 'Vodacom Weekly 1.5GB',
    price: 75,
    volume: '1.5GB',
    validity: '7 Days',
    type: 'Weekly',
    anytimeData: '1.5GB',
    costPerGb: 50,
    bestFor: 'Steady weekly usage without a monthly commitment',
    watchOut: 'Higher cost per GB than monthly bundles',
    ...SOURCES.vodacomOpenMarketBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'voda-monthly-1-5gb',
    slug: 'vodacom-monthly-1-5gb-data-price',
    network: 'Vodacom',
    name: 'Vodacom Once-Off 1.5GB',
    price: 95,
    volume: '1.5GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '1.5GB',
    costPerGb: 63.33,
    bestFor: 'Entry-level 30-day bundle',
    watchOut: 'Personalised offers vary by customer and may differ from public pricing',
    ...SOURCES.vodacomOpenMarketBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'voda-monthly-3gb',
    slug: 'vodacom-monthly-3gb-data-price',
    network: 'Vodacom',
    name: 'Vodacom Once-Off 3GB',
    price: 165,
    volume: '3GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '3GB',
    costPerGb: 55,
    bestFor: 'Smartphone users who need a larger 30-day bundle',
    watchOut: 'Personalised offers vary by customer and may differ from public pricing',
    ...SOURCES.vodacomOpenMarketBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'voda-prepaid-lte-5gb-night-5gb',
    slug: 'vodacom-prepaid-lte-5gb-5gb-night-owl-price',
    network: 'Vodacom',
    name: 'Vodacom Prepaid LTE 5GB Anytime + 5GB Night Owl',
    price: 99,
    volume: '5GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '5GB',
    nightData: '5GB',
    costPerGb: 19.8,
    bestFor: 'Prepaid LTE/router users who can use the Night Owl allocation',
    watchOut: 'Half of the allocation is restricted to Night Owl hours',
    ...SOURCES.vodacomPrepaidLte,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'prepaid_lte_router_data',
    nightWindow: '00:00-05:00',
  },
  {
    id: 'voda-monthly-10gb',
    slug: 'vodacom-10gb-data-price',
    network: 'Vodacom',
    name: 'Vodacom 10GB Anytime + 10GB Night Owl',
    price: 149,
    volume: '10GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '10GB',
    nightData: '10GB',
    costPerGb: 14.9,
    bestFor: 'Regular users who can shift larger downloads overnight',
    watchOut: 'Included data is split between anytime and Night Owl use',
    ...SOURCES.vodacomPrepaidLte,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'prepaid_lte_router_data',
    nightWindow: '00:00-05:00',
  },
  {
    id: 'voda-monthly-20gb',
    slug: 'vodacom-20gb-data-price',
    network: 'Vodacom',
    name: 'Vodacom 20GB Anytime + 20GB Night Owl',
    price: 229,
    volume: '20GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '20GB',
    nightData: '20GB',
    costPerGb: 11.45,
    bestFor: 'Heavy users balancing daytime use with overnight downloads',
    watchOut: 'Only half the total allocation is anytime data',
    ...SOURCES.vodacomPrepaidLte,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'prepaid_lte_router_data',
    nightWindow: '00:00-05:00',
  },
  {
    id: 'voda-monthly-50gb',
    slug: 'vodacom-50gb-data-price',
    network: 'Vodacom',
    name: 'Vodacom 50GB Anytime + 50GB Night Owl',
    price: 349,
    volume: '50GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '50GB',
    nightData: '50GB',
    costPerGb: 6.98,
    bestFor: 'High-usage users who can use substantial Night Owl capacity',
    watchOut: 'Total value depends on actually using the night allocation',
    ...SOURCES.vodacomPrepaidLte,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'prepaid_lte_router_data',
    nightWindow: '00:00-05:00',
  },
  {
    id: 'voda-night-owl-250mb',
    slug: 'vodacom-night-owl-250mb-price',
    network: 'Vodacom',
    name: 'Vodacom Night Owl 250MB',
    price: 14,
    volume: '250MB',
    validity: '1 Night',
    type: 'Daily',
    anytimeData: '0MB',
    nightData: '250MB',
    costPerGb: 56,
    bestFor: 'Late-night updates and overnight downloads',
    watchOut: 'Night-only usage window',
    ...SOURCES.vodacomPrepaidData,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'night_data',
    nightWindow: '00:00-05:00',
  },
  {
    id: 'voda-whatsapp-daily-250mb',
    slug: 'vodacom-whatsapp-daily-250mb-price',
    network: 'Vodacom',
    name: 'Vodacom WhatsApp 250MB Daily',
    price: 5,
    volume: '250MB',
    validity: '1 Day',
    type: 'Social',
    anytimeData: '250MB (WhatsApp)',
    costPerGb: 20,
    bestFor: 'Chat-first users with low daily spend',
    note: 'App-specific bundle',
    watchOut: 'Social-only access, not full internet',
    ...SOURCES.vodacomPrepaidData,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'promo_campaign_offer',
  },
  {
    id: 'telkom-daily-150mb',
    slug: 'telkom-daily-150mb-data-price',
    network: 'Telkom',
    name: 'Telkom Daily 150MB',
    price: 12,
    volume: '150MB',
    validity: '24 Hours',
    type: 'Daily',
    anytimeData: '150MB',
    costPerGb: 80,
    bestFor: 'Quick low-spend top-up',
    watchOut: 'Short 24-hour validity',
    ...SOURCES.telkomTimeBasedBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'telkom-daily-1gb',
    slug: 'telkom-daily-1gb-data-price',
    network: 'Telkom',
    name: 'Telkom Daily 1GB',
    price: 31,
    volume: '1GB',
    validity: '24 Hours',
    type: 'Daily',
    anytimeData: '1GB',
    costPerGb: 31,
    bestFor: 'Short-term high usage day',
    watchOut: 'Short 24-hour validity',
    ...SOURCES.telkomTimeBasedBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'telkom-weekly-1gb',
    slug: 'telkom-weekly-1gb-data-price',
    network: 'Telkom',
    name: 'Telkom Weekly 1GB',
    price: 79,
    volume: '1GB',
    validity: '7 Days',
    type: 'Weekly',
    anytimeData: '1GB',
    costPerGb: 79,
    bestFor: 'Weekly prepaid usage',
    watchOut: 'Higher cost per GB than monthly bundles',
    ...SOURCES.telkomTimeBasedBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'telkom-whatsapp-daily-150mb',
    slug: 'telkom-whatsapp-daily-150mb-data-price',
    network: 'Telkom',
    name: 'Telkom WhatsApp 150MB Daily',
    price: 6,
    volume: '150MB',
    validity: '1 Day',
    type: 'Social',
    anytimeData: '150MB (WhatsApp)',
    costPerGb: 40,
    bestFor: 'Low-cost chat users',
    note: 'App-specific bundle',
    watchOut: 'Social-only access, not full internet',
    ...SOURCES.telkomWhatsappBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'promo_campaign_offer',
  },
  {
    id: 'cellc-daily-80mb',
    slug: 'cell-c-daily-80mb-data-price',
    network: 'Cell C',
    name: 'Cell C Daily 80MB',
    price: 10,
    volume: '80MB',
    validity: 'Until midnight',
    type: 'Daily',
    anytimeData: '80MB',
    costPerGb: 125,
    bestFor: 'Very light daily browsing',
    watchOut: 'Expires at midnight on the day of purchase',
    ...SOURCES.cellcDataBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'cellc-daily-1gb',
    slug: 'cell-c-daily-1gb-data-price',
    network: 'Cell C',
    name: 'Cell C Daily 1GB',
    price: 25,
    volume: '1GB',
    validity: 'Until midnight',
    type: 'Daily',
    anytimeData: '1GB',
    costPerGb: 25,
    bestFor: 'Cheapest short-term general-use option',
    watchOut: 'Expires at midnight on the day of purchase',
    ...SOURCES.cellcDataBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'cellc-monthly-1gb',
    slug: 'cell-c-monthly-1gb-data-price',
    network: 'Cell C',
    name: 'Cell C Monthly 1GB',
    price: 65,
    volume: '1GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '1GB',
    costPerGb: 65,
    bestFor: 'Entry monthly users',
    watchOut: 'Compare the public catalogue with any offers shown on your own line',
    ...SOURCES.cellcDataBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'cellc-whatsapp-monthly-1gb',
    slug: 'cell-c-whatsapp-monthly-1gb-data-price',
    network: 'Cell C',
    name: 'Cell C WhatsApp 1GB Monthly',
    price: 29,
    volume: '1GB',
    validity: '30 Days',
    type: 'Social',
    anytimeData: '1GB (WhatsApp)',
    costPerGb: 29,
    bestFor: 'Chat-heavy users',
    note: 'App-specific bundle',
    watchOut: 'Social-only access, not full internet',
    ...SOURCES.cellcWhatsappBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'promo_campaign_offer',
  },
  {
    id: 'rain-unlimited-4g',
    slug: 'rain-unlimited-4g-data-price',
    network: 'Rain',
    name: 'Rain unlimited home 30Mbps',
    price: 679,
    volume: 'Unlimited',
    validity: 'Month-to-month',
    type: 'Monthly',
    anytimeData: 'Unlimited',
    costPerGb: 0,
    bestFor: 'Home internet users in rain 5G coverage areas',
    watchOut: 'Home 5G plan; confirm coverage and router terms before buying',
    ...SOURCES.rainHome,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'home_internet_fixed_lte',
  },
  {
    id: 'rain-unlimited-5g',
    slug: 'rain-unlimited-5g-data-price',
    network: 'Rain',
    name: 'Rain unlimited home pro 60Mbps',
    price: 799,
    volume: 'Unlimited',
    validity: 'Month-to-month',
    type: 'Monthly',
    anytimeData: 'Unlimited',
    costPerGb: 0,
    bestFor: 'Home users who need higher rain 5G speed tiers',
    watchOut: 'Home 5G plan; compare speed, coverage and router terms with other Rain product families',
    ...SOURCES.rainHome,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'home_internet_fixed_lte',
  },
];

export interface USSDCode {
  id: string;
  network: NetworkName;
  purpose: string;
  code: string;
  category: 'Balance' | 'Data' | 'Settings' | 'Other';
}

export const ussdCodes = [
  { id: 'ussd.vodacom.balance_detailed', network: 'Vodacom', purpose: 'Direct Balance Check', code: '*136#', category: 'Balance' },
  { id: 'ussd.vodacom.buy_data', network: 'Vodacom', purpose: 'Buy Data (follow menu prompts)', code: '*135#', category: 'Data' },
  { id: 'ussd.vodacom.transfer_airtime_data', network: 'Vodacom', purpose: 'Transfer Data', code: '*135*1002#', category: 'Data' },
  { id: 'ussd.vodacom.check_number', network: 'Vodacom', purpose: 'Check My Number', code: '*135*501#', category: 'Other' },
  { id: 'ussd.mtn.balance_main', network: 'MTN', purpose: 'Check Balance', code: '*136#', category: 'Balance' },
  { id: 'ussd.mtn.buy_data', network: 'MTN', purpose: 'Buy Data', code: '*136*2#', category: 'Data' },
  { id: 'ussd.mtn.transfer_airtime_data', network: 'MTN', purpose: 'Transfer Data', code: '*136*3#', category: 'Data' },
  { id: 'ussd.mtn.check_number', network: 'MTN', purpose: 'Find My Number (app, SIM packaging or support)', code: 'N/A', category: 'Other' },
  { id: 'ussd.telkom.balance_main', network: 'Telkom', purpose: 'Check Balance', code: '*188#', category: 'Balance' },
  { id: 'ussd.telkom.buy_data', network: 'Telkom', purpose: 'Buy Data', code: '*180#', category: 'Data' },
  { id: 'ussd.cellc.balance_main', network: 'Cell C', purpose: 'Check Balance', code: '*101#', category: 'Balance' },
  { id: 'ussd.cellc.buy_data', network: 'Cell C', purpose: 'Buy Data', code: '*147#', category: 'Data' },
  { id: 'ussd.rain.app_only', network: 'Rain', purpose: 'Check Balance', code: 'N/A (App or web)', category: 'Balance' },
] as const satisfies readonly USSDCode[];

export const networkStats: NetworkStats[] = [
  {
    network: 'Vodacom',
    coverage: 'Broad national footprint',
    avgSpeed5G: 'Strong urban 5G profile',
    resilience: 'High investment in backup',
    pricePoint: 'Premium pricing',
  },
  {
    network: 'MTN',
    coverage: 'Broad national footprint',
    avgSpeed5G: 'Strong urban 5G profile',
    resilience: 'Aggressive Battery Rollout',
    pricePoint: 'Aggressive Promos',
  },
  {
    network: 'Telkom',
    coverage: 'Strongest in many metro areas',
    avgSpeed5G: 'Area-dependent 5G profile',
    resilience: 'Moderate backup infrastructure',
    pricePoint: 'Budget Friendly',
  },
  {
    network: 'Cell C',
    coverage: 'Dual-MOCN partner footprint',
    avgSpeed5G: 'Partner-network dependent',
    resilience: 'Dependent on partners',
    pricePoint: 'Value focused',
  },
  {
    network: 'Rain',
    coverage: 'Supported urban coverage areas',
    avgSpeed5G: 'High when coverage is strong',
    resilience: 'High (Newer infrastructure)',
    pricePoint: 'Unlimited home 5G',
  },
];
