import { Bundle, NetworkStats, NetworkMetadata, NetworkName } from './types';

const PRICE_REVIEW_DATE = '2026-07-04';

const SOURCES = {
  mtnInternetBundles: {
    sourceUrl: 'https://www.mtn.co.za/home/terms-and-conditions/content/mtn-internet-bundles-terms-and-conditions',
    sourceLabel: 'MTN Internet Bundles terms'
  },
  mtnNightExpress: {
    sourceUrl: 'https://www.mtn.co.za/home/terms-and-conditions/content/mtn-night-express-data-bundles',
    sourceLabel: 'MTN Night Express terms'
  },
  vodacomSmartphoneData: {
    sourceUrl: 'https://www.vodacom.co.za/vodacom/shopping/data/data-for-your-smartphone',
    sourceLabel: 'Vodacom smartphone data page'
  },
  vodacomPrepaidLte: {
    sourceUrl: 'https://www.vodacom.co.za/vodacom/shopping/plans/prepaid-plans',
    sourceLabel: 'Vodacom prepaid LTE data page'
  },
  vodacomNightOwl: {
    sourceUrl: 'https://www.vodacom.co.za/vodacom/terms/night-owl-terms-and-conditions',
    sourceLabel: 'Vodacom Night Owl terms'
  },
  telkomPrepaidBundles: {
    sourceUrl: 'https://www.telkom.co.za/prepaid-services/time-based-bundle',
    sourceLabel: 'Telkom prepaid bundle page'
  },
  cellcDataGuidelines: {
    sourceUrl: 'https://www.cellc.co.za/cellc/data-guidelines',
    sourceLabel: 'Cell C data guidelines'
  },
  cellcDayByDay: {
    sourceUrl: 'https://www.cellc.co.za/cellc/static-content/PDF/Day-By-Day_Data_Bundles_FAQ_Web.pdf',
    sourceLabel: 'Cell C Day-By-Day Data Bundles FAQ'
  },
  rainHome: {
    sourceUrl: 'https://www.rain.co.za/home',
    sourceLabel: 'rainOne Home page'
  }
} as const;

export const networkMetadata: Record<NetworkName, NetworkMetadata> = {
  Vodacom: {
    name: 'Vodacom',
    color: '#E60000',
    textColor: '#FFFFFF',
    logoLetter: 'V',
    description: 'Vodacom is usually a coverage-first option in many urban and suburban areas.',
    ussdBalance: '*135#',
    externalUrl: 'https://www.vodacom.co.za',
  },
  MTN: {
    name: 'MTN',
    color: '#FFCC00',
    textColor: '#031636',
    logoLetter: 'M',
    description: 'MTN is often a balanced option for users comparing coverage, promotions, and monthly value.',
    ussdBalance: '*136#',
    externalUrl: 'https://www.mtn.co.za',
  },
  Telkom: {
    name: 'Telkom',
    color: '#0066CC',
    textColor: '#FFFFFF',
    logoLetter: 'T',
    description: 'Telkom is often competitive for prepaid users who prioritize lower cost per GB.',
    ussdBalance: '*188#',
    externalUrl: 'https://www.telkom.co.za',
  },
  'Cell C': {
    name: 'Cell C',
    color: '#1a1c1c',
    textColor: '#FFFFFF',
    logoLetter: 'C',
    description: "Cell C roams on MTN/Vodacom infrastructure in most areas, offering good value.",
    ussdBalance: '*101#',
    externalUrl: 'https://www.cellc.co.za',
  },
  Rain: {
    name: 'Rain',
    color: '#FF4400',
    textColor: '#FFFFFF',
    logoLetter: 'R',
    description: 'Rain focuses on app-managed unlimited-style data plans in supported coverage areas.',
    ussdBalance: 'N/A (App only)',
    externalUrl: 'https://www.rain.co.za',
  },
};

export const bundles: Bundle[] = [
  {
    id: 'mtn-monthly-50gb',
    slug: 'mtn-50gb-data-price',
    network: 'MTN',
    name: 'MTN Monthly 50GB',
    price: 299,
    volume: '50GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '25GB',
    nightData: '25GB',
    costPerGb: 5.98,
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'manual_required',
    productType: 'promo_campaign_offer',
  },
  {
    id: 'mtn-monthly-10gb',
    slug: 'mtn-10gb-data-price',
    network: 'MTN',
    name: 'MTN Monthly 10GB',
    price: 149,
    volume: '10GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '10GB',
    costPerGb: 14.90,
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'mtn-monthly-1gb',
    slug: 'mtn-1gb-data-price',
    network: 'MTN',
    name: 'MTN Monthly 1GB',
    price: 80,
    volume: '1GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '1GB',
    costPerGb: 80,
    bestFor: 'Entry-level monthly option',
    watchOut: 'Higher cost per GB than larger bundles',
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'mtn-hourly-75mb',
    slug: 'mtn-hourly-75mb-data-price',
    network: 'MTN',
    name: 'MTN Hourly 75MB',
    price: 10,
    volume: '75MB',
    validity: '1 Hour',
    type: 'Hourly',
    anytimeData: '75MB',
    costPerGb: 133.33,
    bestFor: 'Quick short-session usage',
    watchOut: 'Very short validity (1 hour)',
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'mtn-daily-250mb',
    slug: 'mtn-daily-250mb-data-price',
    network: 'MTN',
    name: 'MTN Daily 250MB',
    price: 15,
    volume: '250MB',
    validity: '1 Day',
    type: 'Daily',
    anytimeData: '250MB',
    costPerGb: 60,
    bestFor: 'Light daily usage',
    watchOut: 'Short validity (1 day)',
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'mtn-daily-1gb',
    slug: 'mtn-daily-1gb-data-price',
    network: 'MTN',
    name: 'MTN Daily 1GB',
    price: 25,
    volume: '1GB',
    validity: '1 Day',
    type: 'Daily',
    anytimeData: '1GB',
    costPerGb: 25,
    bestFor: 'Cheapest short-term 1GB',
    watchOut: 'Short validity (1 day)',
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'mtn-weekly-500mb',
    slug: 'mtn-weekly-500mb-data-price',
    network: 'MTN',
    name: 'MTN Weekly 500MB',
    price: 37,
    volume: '500MB',
    validity: '7 Days',
    type: 'Weekly',
    anytimeData: '500MB',
    costPerGb: 74,
    bestFor: 'Moderate weekly usage',
    watchOut: 'Higher cost per GB than monthly bundles',
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'mtn-weekly-1gb',
    slug: 'mtn-weekly-1gb-data-price',
    network: 'MTN',
    name: 'MTN Weekly 1GB',
    price: 55,
    volume: '1GB',
    validity: '7 Days',
    type: 'Weekly',
    anytimeData: '1GB',
    costPerGb: 55,
    bestFor: 'Weekly top-up without monthly commitment',
    watchOut: 'Can be expensive if repeated every week',
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'mtn-night-250mb',
    slug: 'mtn-night-250mb-data-price',
    network: 'MTN',
    name: 'MTN Night Express 250MB',
    price: 5,
    volume: '250MB',
    validity: '1 Night',
    type: 'Daily',
    anytimeData: '0MB',
    nightData: '250MB',
    costPerGb: 20,
    bestFor: 'Late-night downloads',
    watchOut: 'Night-only usage window',
    ...SOURCES.mtnNightExpress,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'night_data',
    nightWindow: '00:01-04:59',
  },
  {
    id: 'mtn-whatsapp-weekly-1gb',
    slug: 'mtn-whatsapp-weekly-1gb-data-price',
    network: 'MTN',
    name: 'MTN WhatsApp 1GB Weekly',
    price: 20,
    volume: '1GB',
    validity: '7 Days',
    type: 'Social',
    anytimeData: '1GB (WhatsApp)',
    costPerGb: 20,
    bestFor: 'Chat-first users',
    note: 'App-specific bundle',
    watchOut: 'Social-only access, not full internet',
    sourceLabel: 'Manual official confirmation required',
    sourceConfidence: 'manual_required',
    productType: 'promo_campaign_offer',
  },
  {
    id: 'mtn-monthly-recurring-20gb',
    slug: 'mtn-monthly-recurring-20gb-data-price',
    network: 'MTN',
    name: 'MTN 20GB Monthly Recurring',
    price: 279,
    volume: '20GB',
    validity: '30 Days (Recurring)',
    type: 'Monthly',
    anytimeData: '20GB',
    costPerGb: 13.95,
    bestFor: 'Regular heavy users',
    watchOut: 'Auto-renews each cycle',
    ...SOURCES.mtnInternetBundles,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_recurring_data',
  },
  {
    id: 'voda-hourly-50mb',
    slug: 'vodacom-hourly-50mb-data-price',
    network: 'Vodacom',
    name: 'Vodacom Hourly 50MB',
    price: 5,
    volume: '50MB',
    validity: '1 Hour',
    type: 'Hourly',
    anytimeData: '50MB',
    costPerGb: 100,
    bestFor: 'Emergency top-up for quick low-data tasks',
    watchOut: 'Very short validity (1 hour)',
    sourceLabel: 'Manual official confirmation required',
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'voda-daily-250mb',
    slug: 'vodacom-daily-250mb-data-price',
    network: 'Vodacom',
    name: 'Vodacom Daily 250MB',
    price: 27,
    volume: '250MB',
    validity: '1 Day',
    type: 'Daily',
    anytimeData: '250MB',
    costPerGb: 108,
    bestFor: 'Light users who need data for a single day',
    watchOut: 'Short validity (1 day)',
    ...SOURCES.vodacomSmartphoneData,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'voda-daily-1gb',
    slug: 'vodacom-daily-1gb-data-price',
    network: 'Vodacom',
    name: 'Vodacom Daily 1GB',
    price: 29,
    volume: '1GB',
    validity: '1 Day',
    type: 'Daily',
    anytimeData: '1GB',
    costPerGb: 29,
    bestFor: 'Best standard short-term 1GB option',
    watchOut: 'Short validity (1 day)',
    sourceLabel: 'Manual official confirmation required',
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'voda-weekly-500mb',
    slug: 'vodacom-weekly-500mb-data-price',
    network: 'Vodacom',
    name: 'Vodacom Weekly 500MB',
    price: 49,
    volume: '500MB',
    validity: '7 Days',
    type: 'Weekly',
    anytimeData: '500MB',
    costPerGb: 98,
    bestFor: 'Moderate users who recharge weekly',
    watchOut: 'Higher cost per GB than larger packs',
    sourceLabel: 'Manual official confirmation required',
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'voda-weekly-1gb',
    slug: 'vodacom-weekly-1gb-data-price',
    network: 'Vodacom',
    name: 'Vodacom Weekly 1GB',
    price: 69,
    volume: '1GB',
    validity: '7 Days',
    type: 'Weekly',
    anytimeData: '1GB',
    costPerGb: 69,
    bestFor: 'Steady weekly usage without a monthly commitment',
    watchOut: 'Higher cost per GB than monthly bundles',
    sourceLabel: 'Manual official confirmation required',
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'voda-monthly-1gb',
    slug: 'vodacom-monthly-1gb-data-price',
    network: 'Vodacom',
    name: 'Vodacom Once-Off 1GB',
    price: 85,
    volume: '1GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '1GB',
    costPerGb: 85,
    bestFor: 'Entry-level 30-day bundle',
    watchOut: 'Public once-off pricing can still be beaten by personalised offers',
    ...SOURCES.vodacomSmartphoneData,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'voda-monthly-2gb',
    slug: 'vodacom-monthly-2gb-data-price',
    network: 'Vodacom',
    name: 'Vodacom Once-Off 2GB',
    price: 149,
    volume: '2GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '2GB',
    costPerGb: 74.5,
    bestFor: 'Smartphone users who need a 30-day 2GB bundle',
    watchOut: 'Public once-off pricing can still be beaten by personalised offers',
    ...SOURCES.vodacomSmartphoneData,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'voda-prepaid-lte-5gb-night-5gb',
    slug: 'vodacom-prepaid-lte-5gb-5gb-night-owl-price',
    network: 'Vodacom',
    name: 'Vodacom Prepaid LTE 5GB Anytime + 5GB Night Owl',
    price: 99,
    volume: '5GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '5GB',
    nightData: '5GB',
    costPerGb: 19.8,
    bestFor: 'Prepaid LTE/router users who can use the Night Owl allocation',
    watchOut: 'Half of the allocation is restricted to Night Owl hours',
    ...SOURCES.vodacomPrepaidLte,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'prepaid_lte_router_data',
    nightWindow: '00:00-05:00',
  },
  {
    id: 'voda-monthly-10gb',
    slug: 'vodacom-10gb-data-price',
    network: 'Vodacom',
    name: 'Vodacom 10GB Anytime + 10GB Night Owl',
    price: 149,
    volume: '10GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '10GB',
    nightData: '10GB',
    costPerGb: 14.9,
    bestFor: 'Regular users who can shift larger downloads overnight',
    watchOut: 'Included data is split between anytime and Night Owl use',
    ...SOURCES.vodacomPrepaidLte,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'prepaid_lte_router_data',
    nightWindow: '00:00-05:00',
  },
  {
    id: 'voda-monthly-20gb',
    slug: 'vodacom-20gb-data-price',
    network: 'Vodacom',
    name: 'Vodacom 20GB Anytime + 20GB Night Owl',
    price: 229,
    volume: '20GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '20GB',
    nightData: '20GB',
    costPerGb: 11.45,
    bestFor: 'Heavy users balancing daytime use with overnight downloads',
    watchOut: 'Only half the total allocation is anytime data',
    ...SOURCES.vodacomPrepaidLte,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'prepaid_lte_router_data',
    nightWindow: '00:00-05:00',
  },
  {
    id: 'voda-monthly-50gb',
    slug: 'vodacom-50gb-data-price',
    network: 'Vodacom',
    name: 'Vodacom 50GB Anytime + 50GB Night Owl',
    price: 349,
    volume: '50GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '50GB',
    nightData: '50GB',
    costPerGb: 6.98,
    bestFor: 'High-usage users who can use substantial Night Owl capacity',
    watchOut: 'Total value depends on actually using the night allocation',
    ...SOURCES.vodacomPrepaidLte,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'prepaid_lte_router_data',
    nightWindow: '00:00-05:00',
  },
  {
    id: 'voda-night-owl-250mb',
    slug: 'vodacom-night-owl-250mb-price',
    network: 'Vodacom',
    name: 'Vodacom Night Owl 250MB',
    price: 14,
    volume: '250MB',
    validity: '1 Night',
    type: 'Daily',
    anytimeData: '0MB',
    nightData: '250MB',
    costPerGb: 56,
    bestFor: 'Late-night updates and overnight downloads',
    watchOut: 'Night-only usage window',
    ...SOURCES.vodacomNightOwl,
    sourceConfidence: 'manual_required',
    productType: 'night_data',
    nightWindow: '00:00-05:00',
  },
  {
    id: 'voda-whatsapp-daily-250mb',
    slug: 'vodacom-whatsapp-daily-250mb-price',
    network: 'Vodacom',
    name: 'Vodacom WhatsApp 250MB Daily',
    price: 5,
    volume: '250MB',
    validity: '1 Day',
    type: 'Social',
    anytimeData: '250MB (WhatsApp)',
    costPerGb: 20,
    bestFor: 'Chat-first users with low daily spend',
    note: 'App-specific bundle',
    watchOut: 'Social-only access, not full internet',
    sourceLabel: 'Manual official confirmation required',
    sourceConfidence: 'manual_required',
    productType: 'promo_campaign_offer',
  },
  {
    id: 'telkom-daily-150mb',
    slug: 'telkom-daily-150mb-data-price',
    network: 'Telkom',
    name: 'Telkom Daily 150MB',
    price: 8,
    volume: '150MB',
    validity: '1 Day',
    type: 'Daily',
    anytimeData: '150MB',
    costPerGb: 53.33,
    bestFor: 'Quick low-spend top-up',
    watchOut: 'Short validity (1 day)',
    ...SOURCES.telkomPrepaidBundles,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'telkom-daily-1gb',
    slug: 'telkom-daily-1gb-data-price',
    network: 'Telkom',
    name: 'Telkom Daily 1GB',
    price: 23,
    volume: '1GB',
    validity: '1 Day',
    type: 'Daily',
    anytimeData: '1GB',
    costPerGb: 23,
    bestFor: 'Short-term high usage day',
    watchOut: 'Short validity (1 day)',
    ...SOURCES.telkomPrepaidBundles,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'telkom-weekly-1gb',
    slug: 'telkom-weekly-1gb-data-price',
    network: 'Telkom',
    name: 'Telkom Weekly 1GB',
    price: 49,
    volume: '1GB',
    validity: '7 Days',
    type: 'Weekly',
    anytimeData: '1GB',
    costPerGb: 49,
    bestFor: 'Weekly prepaid usage',
    watchOut: 'Higher cost per GB than monthly bundles',
    ...SOURCES.telkomPrepaidBundles,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'telkom-monthly-2gb',
    slug: 'telkom-monthly-2gb-data-price',
    network: 'Telkom',
    name: 'Telkom Monthly 2GB',
    price: 59,
    volume: '2GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '2GB',
    costPerGb: 29.5,
    bestFor: 'Entry monthly users',
    watchOut: 'Smaller bundles can have weaker value',
    ...SOURCES.telkomPrepaidBundles,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'telkom-monthly-10gb',
    slug: 'telkom-monthly-10gb-data-price',
    network: 'Telkom',
    name: 'Telkom 10GB Monthly',
    price: 89,
    volume: '10GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '10GB',
    costPerGb: 8.9,
    bestFor: 'Best monthly value for many users',
    watchOut: 'Check local coverage before buying',
    ...SOURCES.telkomPrepaidBundles,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'telkom-prepaid-20gb',
    slug: 'telkom-20gb-data-price',
    network: 'Telkom',
    name: 'Telkom 20GB Prepaid',
    price: 99,
    volume: '20GB',
    validity: '30 Days',
    type: 'Prepaid',
    anytimeData: '20GB',
    costPerGb: 4.95,
    bestFor: 'Heavy users chasing low cost per GB',
    watchOut: 'Coverage can vary by area',
    ...SOURCES.telkomPrepaidBundles,
    sourceConfidence: 'manual_required',
    productType: 'prepaid_lte_router_data',
  },
  {
    id: 'telkom-prepaid-40gb',
    slug: 'telkom-40gb-data-price',
    network: 'Telkom',
    name: 'Telkom 40GB Prepaid',
    price: 189,
    volume: '40GB',
    validity: '30 Days',
    type: 'Prepaid',
    anytimeData: '40GB',
    costPerGb: 4.73,
    bestFor: 'Very heavy monthly users',
    watchOut: 'Large upfront spend and location-dependent value',
    ...SOURCES.telkomPrepaidBundles,
    sourceConfidence: 'manual_required',
    productType: 'prepaid_lte_router_data',
  },
  {
    id: 'telkom-prepaid-1gb',
    slug: 'telkom-1gb-data-price',
    network: 'Telkom',
    name: 'Telkom 1GB Prepaid',
    price: 79,
    volume: '1GB',
    validity: '30 Days',
    type: 'Prepaid',
    anytimeData: '1GB',
    costPerGb: 79,
    bestFor: 'Entry-level monthly option',
    watchOut: 'Poor value versus larger Telkom bundles',
    ...SOURCES.telkomPrepaidBundles,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'telkom-night-surfer-1gb',
    slug: 'telkom-night-1gb-data-price',
    network: 'Telkom',
    name: 'Telkom Night Surfer 1GB',
    price: 10,
    volume: '1GB',
    validity: '1 Night',
    type: 'Daily',
    anytimeData: '0MB',
    nightData: '1GB',
    costPerGb: 10,
    bestFor: 'Overnight downloads',
    watchOut: 'Night-only usage window; Telkom network only where applicable',
    ...SOURCES.telkomPrepaidBundles,
    sourceConfidence: 'manual_required',
    productType: 'night_data',
    nightWindow: '00:00-07:00',
  },
  {
    id: 'telkom-whatsapp-daily-250mb',
    slug: 'telkom-whatsapp-daily-250mb-data-price',
    network: 'Telkom',
    name: 'Telkom WhatsApp 250MB Daily',
    price: 4,
    volume: '250MB',
    validity: '1 Day',
    type: 'Social',
    anytimeData: '250MB (WhatsApp)',
    costPerGb: 16,
    bestFor: 'Low-cost chat users',
    note: 'App-specific bundle',
    watchOut: 'Social-only access, not full internet',
    ...SOURCES.telkomPrepaidBundles,
    sourceConfidence: 'manual_required',
    productType: 'promo_campaign_offer',
  },
  {
    id: 'cellc-daily-100mb',
    slug: 'cell-c-daily-100mb-data-price',
    network: 'Cell C',
    name: 'Cell C Daily 100MB',
    price: 7,
    volume: '100MB',
    validity: '1 Day',
    type: 'Daily',
    anytimeData: '100MB',
    costPerGb: 70,
    bestFor: 'Very light daily browsing',
    watchOut: 'Short validity (1 day)',
    ...SOURCES.cellcDataGuidelines,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'cellc-daily-1gb',
    slug: 'cell-c-daily-1gb-data-price',
    network: 'Cell C',
    name: 'Cell C Daily 1GB',
    price: 25,
    volume: '1GB',
    validity: '1 Day',
    type: 'Daily',
    anytimeData: '1GB',
    costPerGb: 25,
    bestFor: 'Cheapest short-term general-use option',
    watchOut: 'Short validity (1 day)',
    ...SOURCES.cellcDataGuidelines,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'cellc-weekly-1gb',
    slug: 'cell-c-weekly-1gb-data-price',
    network: 'Cell C',
    name: 'Cell C Weekly 1GB',
    price: 45,
    volume: '1GB',
    validity: '7 Days',
    type: 'Weekly',
    anytimeData: '1GB',
    costPerGb: 45,
    bestFor: 'Weekly moderate usage',
    watchOut: 'Can be costly versus monthly bundles',
    ...SOURCES.cellcDataGuidelines,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'cellc-monthly-1gb',
    slug: 'cell-c-monthly-1gb-data-price',
    network: 'Cell C',
    name: 'Cell C Monthly 1GB',
    price: 65,
    volume: '1GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '1GB',
    costPerGb: 65,
    bestFor: 'Entry monthly users',
    watchOut: 'Compare with promo deals first',
    ...SOURCES.cellcDataGuidelines,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'cellc-monthly-5gb',
    slug: 'cell-c-5gb-data-price',
    network: 'Cell C',
    name: 'Cell C 5GB Monthly',
    price: 99,
    volume: '5GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '5GB',
    costPerGb: 19.8,
    bestFor: 'Balanced monthly usage',
    watchOut: 'Promo terms may change by period',
    ...SOURCES.cellcDataGuidelines,
    sourceConfidence: 'manual_required',
    productType: 'promo_campaign_offer',
  },
  {
    id: 'cellc-monthly-10gb',
    slug: 'cell-c-10gb-data-price',
    network: 'Cell C',
    name: 'Cell C 10GB Monthly',
    price: 129,
    volume: '10GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '10GB',
    costPerGb: 12.90,
    bestFor: 'Strong monthly value',
    watchOut: 'Check coverage quality in your area',
    ...SOURCES.cellcDataGuidelines,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_once_off_data',
  },
  {
    id: 'cellc-monthly-30gb',
    slug: 'cell-c-30gb-data-price',
    network: 'Cell C',
    name: 'Cell C 30GB Monthly',
    price: 299,
    volume: '30GB',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: '30GB',
    costPerGb: 9.97,
    bestFor: 'Heavy prepaid users',
    watchOut: 'Large upfront spend',
    ...SOURCES.cellcDayByDay,
    sourceConfidence: 'manual_required',
    productType: 'promo_campaign_offer',
  },
  {
    id: 'cellc-night-250mb',
    slug: 'cell-c-night-250mb-data-price',
    network: 'Cell C',
    name: 'Cell C Night 250MB',
    price: 9,
    volume: '250MB',
    validity: '1 Night',
    type: 'Daily',
    anytimeData: '0MB',
    nightData: '250MB',
    costPerGb: 36,
    bestFor: 'Late-night updates',
    watchOut: 'Night-only usage window; Day-By-Day Daily Nite windows differ from LTE/Home Connecta rules',
    ...SOURCES.cellcDayByDay,
    sourceConfidence: 'manual_required',
    productType: 'night_data',
    nightWindow: '00:00-04:59 for Day-By-Day Daily Nite; LTE/Home Connecta rules may differ',
  },
  {
    id: 'cellc-whatsapp-weekly-1gb',
    slug: 'cell-c-whatsapp-weekly-1gb-data-price',
    network: 'Cell C',
    name: 'Cell C WhatsApp 1GB Weekly',
    price: 15,
    volume: '1GB',
    validity: '7 Days',
    type: 'Social',
    anytimeData: '1GB (WhatsApp)',
    costPerGb: 15,
    bestFor: 'Chat-heavy users',
    note: 'App-specific bundle',
    watchOut: 'Social-only access, not full internet',
    ...SOURCES.cellcDataGuidelines,
    sourceConfidence: 'manual_required',
    productType: 'promo_campaign_offer',
  },
  {
    id: 'cellc-monthly-recurring-20gb',
    slug: 'cell-c-monthly-recurring-20gb-data-price',
    network: 'Cell C',
    name: 'Cell C 20GB Monthly Recurring',
    price: 249,
    volume: '20GB',
    validity: '30 Days (Recurring)',
    type: 'Monthly',
    anytimeData: '20GB',
    costPerGb: 12.45,
    bestFor: 'Regular heavy users',
    watchOut: 'Auto-renews each cycle',
    ...SOURCES.cellcDataGuidelines,
    sourceConfidence: 'manual_required',
    productType: 'smartphone_recurring_data',
  },
  {
    id: 'rain-unlimited-4g',
    slug: 'rain-unlimited-4g-data-price',
    network: 'Rain',
    name: 'rainOne Home the101 30Mbps',
    price: 679,
    volume: 'Unlimited',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: 'Unlimited',
    costPerGb: 0,
    bestFor: 'Home internet users in rain 5G coverage areas',
    watchOut: 'Home 5G plan; confirm coverage and router terms before buying',
    ...SOURCES.rainHome,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'home_internet_fixed_lte',
  },
  {
    id: 'rain-unlimited-5g',
    slug: 'rain-unlimited-5g-data-price',
    network: 'Rain',
    name: 'rainOne Home the101 pro 60Mbps',
    price: 899,
    volume: 'Unlimited',
    validity: '30 Days',
    type: 'Monthly',
    anytimeData: 'Unlimited',
    costPerGb: 0,
    bestFor: 'Home users who need higher rain 5G speed tiers',
    watchOut: 'Home 5G plan; rainGO and loop are separate product families',
    ...SOURCES.rainHome,
    sourceConfidence: 'verified',
    lastVerified: PRICE_REVIEW_DATE,
    productType: 'home_internet_fixed_lte',
  },
];

export interface USSDCode {
  network: NetworkName;
  purpose: string;
  code: string;
  category: 'Balance' | 'Data' | 'Settings' | 'Other';
}

export const ussdCodes: USSDCode[] = [
  { network: 'Vodacom', purpose: 'Check Balance', code: '*135#', category: 'Balance' },
  { network: 'Vodacom', purpose: 'Buy Data', code: '*135*2#', category: 'Data' },
  { network: 'Vodacom', purpose: 'Transfer Data', code: '*135*1002#', category: 'Data' },
  { network: 'Vodacom', purpose: 'Check My Number', code: '*135*501#', category: 'Other' },
  { network: 'MTN', purpose: 'Check Balance', code: '*136#', category: 'Balance' },
  { network: 'MTN', purpose: 'Buy Data', code: '*136*2#', category: 'Data' },
  { network: 'MTN', purpose: 'Transfer Data', code: '*136*3#', category: 'Data' },
  { network: 'MTN', purpose: 'Check My Number', code: '*123*888#', category: 'Other' },
  { network: 'Telkom', purpose: 'Check Balance', code: '*188#', category: 'Balance' },
  { network: 'Telkom', purpose: 'Buy Data', code: '*180#', category: 'Data' },
  { network: 'Cell C', purpose: 'Check Balance', code: '*101#', category: 'Balance' },
  { network: 'Cell C', purpose: 'Buy Data', code: '*147#', category: 'Data' },
  { network: 'Rain', purpose: 'Check Balance', code: 'N/A (App only)', category: 'Balance' },
];

export const networkStats: NetworkStats[] = [
  {
    network: 'Vodacom',
    coverage: 'Broad national footprint',
    avgSpeed5G: 'Strong urban 5G profile',
    resilience: 'High investment in backup',
    pricePoint: 'Premium pricing',
  },
  {
    network: 'MTN',
    coverage: 'Broad national footprint',
    avgSpeed5G: 'Strong urban 5G profile',
    resilience: 'Aggressive Battery Rollout',
    pricePoint: 'Aggressive Promos',
  },
  {
    network: 'Telkom',
    coverage: 'Strongest in many metro areas',
    avgSpeed5G: 'Area-dependent 5G profile',
    resilience: 'Moderate backup infrastructure',
    pricePoint: 'Budget Friendly',
  },
  {
    network: 'Cell C',
    coverage: 'Roaming-backed footprint',
    avgSpeed5G: 'Partner-network dependent',
    resilience: 'Dependent on partners',
    pricePoint: 'Value focused',
  },
  {
    network: 'Rain',
    coverage: 'Supported urban coverage areas',
    avgSpeed5G: 'High when coverage is strong',
    resilience: 'High (Newer infrastructure)',
    pricePoint: 'Unlimited Fixed-LTE',
  },
];
